import sokratesImg from './pages/img/sokrates.png';
import platonImg from './pages/img/platon.png';
import aristotelImg from './pages/img/aristotel.png';
import senekaImg from './pages/img/seneka.png';
import schellingImg from './pages/img/Schelling.png';
import leibnizImg from './pages/img/leibniz.png';
import konfucijusImg from './pages/img/konfucijus.png';
import husserlImg from './pages/img/husserl.png';
import hegelImg from './pages/img/hegel.png';
import diderotImg from './pages/img/diderot.png';
import dignagaImg from './pages/img/dignaga.png';
import gaudapadaImg from './pages/img/gaudapada.png';
import ghoshasImg from './pages/img/ghoshas.png';
import jeffersonImg from './pages/img/jeferson.png';
import lockeImg from './pages/img/loke.png';
import montesqueImg from './pages/img/montesque.png';
import ramanujaImg from './pages/img/ramanudzi.png';
import sankaraImg from './pages/img/sankara.png';
import schopenhauerImg from './pages/img/sopenhauer.png';
import spinozaImg from './pages/img/spinoza.png';
import voltaireImg from './pages/img/volteras.png';
import descartesImg from './pages/img/dekartas.png';
import husImg from './pages/img/husas.png';
import wattsImg from './pages/img/Watts.png';
import epicurusImg from './pages/img/epikiuras.png';
import pythagorasImg from './pages/img/pitagoras.png';
import marxImg from './pages/img/marx.png';
import laoziImg from './pages/img/laodzi.png';
import huxleyImg from './pages/img/huxley.png';
import nietzscheImg from './pages/img/nyce.png';
import kantImg from './pages/img/kant.png';
import ciceroIMG from './pages/img/ciceronas.png';
import engelsImg from './pages/img/engels.png';
import aquinasImg from './pages/img/akvinietis.png';
import ashvaghoshaImg from './pages/img/ashvagosha.png';
import machiavelliImg from './pages/img/makevelis.png';
import calvinImg from './pages/img/kalvinas.png';
import erasmusImg from './pages/img/roterdamus.png';
import aureliusImg from './pages/img/antonijus.png';

export const philosophers = [
  { name: "Socrates", years: "(470–399 BC)", quote: "The unexamined life is not worth living.", bio: "In the sunlit streets of ancient Athens, Socrates walked barefoot, questioning everyone he met. He didn’t write books or start a school—he just asked questions that shook the foundations of belief. Living from 470 to 399 BC, he believed the unexamined life wasn't worth living. For him, wisdom began with admitting ignorance. He died by drinking poison, choosing truth over escape.", img: sokratesImg, id: 1 },
  { name: "Plato", years: "(428–348 BC)", quote: "Wise men speak because they have something to say.", bio: "Socrates' student, Plato, turned thought into dialogue. Born in 428 BC, he founded the Academy—perhaps the first university. His writings explored justice, love, and the ideal society. In the shadows of Athens, he dreamed of a world where philosopher-kings ruled, guided not by power, but by reason.", img: platonImg, id: 2 },
  { name: "Aristotle", years: "(384–322 BC)", quote: "Knowing yourself is the beginning of all wisdom.", bio: "Aristotle, Plato’s student, was more grounded. Born in 384 BC in northern Greece, he loved nature, logic, and categories. He tutored Alexander the Great, and his mind ranged across science, politics, and ethics. He believed in moderation—a life of virtue balanced between extremes.", img: aristotelImg, id: 3 },
  { name: "Seneca", years: "(4 BC–65 AD)", quote: "Luck is what happens when preparation meets opportunity.", bio: "In imperial Rome, Seneca stood at the heart of power as a statesman and advisor to Nero. Born around 4 BC, he was a Stoic, believing that true strength comes from within. Life is short, he said—don’t waste it. Prepare your mind, and fortune cannot shake you.", img: senekaImg, id: 4 },
  { name: "Friedrich Schelling", years: "(1775–1854)", quote: "The history of the world is the discipline of the human race.", bio: "Schelling, born in 1775 in Germany, looked into nature and saw spirit. He believed that the universe was alive and creativity was divine. As a post-Kantian idealist, he merged art, nature, and philosophy, seeking unity in a world of dualities.In imperial Rome, Seneca stood at the heart of power as a statesman and advisor to Nero. Born around 4 BC, he was a Stoic, believing that true strength comes from within. Life is short, he said—don’t waste it. Prepare your mind, and fortune cannot shake you.Schelling, born in 1775 in Germany, looked into nature and saw spirit. He believed that the universe was alive and creativity was divine. As a post-Kantian idealist, he merged art, nature, and philosophy, seeking unity in a world of dualities.", img: schellingImg, id: 5 },
  { name: "Gottfried Wilhelm Leibniz", years: "(1646–1716)", quote: "Music is the pleasure the human mind experiences from counting without being aware that it is counting.", bio: "Born in 1646 in Leipzig, Leibniz was a genius who saw the world as a perfectly ordered machine. He co-invented calculus (independently of Newton) and believed that we live in the best of all possible worlds. For him, logic, math, and metaphysics were intertwined—every small part reflected the whole.", img: leibnizImg, id: 6 },
  { name: "Confucius", years: "(551–479 BC)", quote: "It does not matter how slowly you go as long as you do not stop.", bio: "Walking through ancient China around 500 BC, Confucius taught not from a throne, but through dialogue. A teacher and moral guide, he believed harmony came from proper conduct—respect your parents, honor your role, and serve society. His thoughts shaped East Asia for centuries and still echo in classrooms and homes today.Walking through ancient China around 500 BC, Confucius taught not from a throne, but through dialogue. A teacher and moral guide, he believed harmony came from proper conduct—respect your parents, honor your role, and serve society. His thoughts shaped East Asia for centuries and still echo in classrooms and homes today.", img: konfucijusImg, id: 7 },
  { name: "Edmund Husserl", years: "(1859–1938)", quote: "The only world that exists is the one we experience.", bio: "In the early 20th century, Husserl wanted to clear away assumptions and look at experience itself. Born in 1859 in what’s now the Czech Republic, he founded phenomenology—the study of consciousness from the first-person view. He asked: What is it like to experience something? His thinking laid the groundwork for eIn the early 20th century, Husserl wanted to clear away assumptions and look at experience itself. Born in 1859 in what’s now the Czech Republic, he founded phenomenology—the study of consciousness from the first-person view. He asked: What is it like to experience something? His thinking laid the groundwork for existentialism.", img: husserlImg, id: 8 },
  { name: "G.W.Friedrich Hegel", years: "(1770–1831)", quote: "Nothing great in the world has been accomplished without passion.", bio: "Hegel, born in 1770 in Stuttgart, thought in spirals. To him, history was a process—a dialectic—where ideas clashed and evolved. Thesis meets antithesis, creating a synthesis. He believed in progress through conflict, and that reality unfolds through reason. Complex? Yes. But also revolutionary.German idealist philosopher. Developed dialectics and influenced politics, history, logic, and metaphysics.", img: hegelImg, id: 33 },
  { name: "Denis Diderot", years: "(1713–1784)", quote: "Man will never be free until the last king is strangled with the entrails of the last priest.", bio: "In 18th-century France, Diderot dreamed of gathering all knowledge in one place. Born in 1713, he co-created the Encyclopédie—a radical act at the time. He believed reason and science could liberate humanity from superstition. Witty, bold, and rebellious, he helped light the fire of the Enlightenment.In 18th-century France, Diderot dreamed of gathering all knowledge in one place...", img: diderotImg, id: 10 },
  { name: "Dignaga", years: "(480–540)", quote: "Only perception and inference are valid means of knowledge.", bio: "In 5th-century India, Dignaga transformed Buddhist thought by focusing on logic and perception. He believed there are only two valid paths to knowledge: what we see, and what we logically infer. His work laid the foundation for centuries of philosophical debate in India and Tibet.In 5th-century India, Dignaga transformed Buddhist thought by focusing on logic and perception. He believed there are only two valid paths to knowledge: what we see, and what we logically infer. His work laid the foundation for centuries of philosophical debate in India and Tibet.In 5th-century India, Dignaga transformed Buddhist thought by focusing on logic and perception...", img: dignagaImg, id: 11 },
  { name: "Gaudapada", years: "(6th century AD)", quote: "The self is unborn, eternal, and beyond time.", bio: "A quiet mystic of 6th-century India, Gaudapada meditated on reality and came to a startling conclusion: the self is eternal, untouched by time or change. His philosophy—early Advaita Vedanta—claimed that the world is illusion and only the Self (Brahman) is real. Peace, he taught, comes from realizing this unity.A quiet mystic of 6th-century India, Gaudapada meditated on reality and came to a startling conclusion...", img: gaudapadaImg, id: 12 },
  { name: "Ghosha", years: "(circa 1st century AD)", quote: "Poetry is the mirror of the inner self.", bio: "Ghosha lived in ancient India around the 1st century AD—a rare female voice in early philosophy. A poet and sage, her hymns in the Rigveda reflected on inner beauty, health, and devotion. Through her words, she bridged the human and the divine, showing that wisdom and grace can coexist.Ghosha lived in ancient India around the 1st century AD—a rare female voice in early philosophy...", img: ghoshasImg, id: 13 },
  { name: "Thomas Jefferson", years: "(1743–1826)", quote: "I cannot live without books.", bio: "Born in 1743 in colonial Virginia, Jefferson was more than a Founding Father—he was a thinker, writer, and lover of books. He penned the Declaration of Independence, embedding Enlightenment ideals of liberty and human rights. He believed in education, reason, and the power of the individual to shape society.Born in 1743 in colonial Virginia, Jefferson was more than a Founding Father...", img: jeffersonImg, id: 14 },
  { name: "John Locke", years: "(1632–1704)", quote: "The end of law is not to abolish or restrain, but to preserve and enlarge freedom.", bio: "John Locke, born in 1632 in England, is often called the father of liberalism. He argued that governments must protect life, liberty, and property—and if they don’t, people have the right to rebel. He believed knowledge came from experience, not birthright. His ideas helped spark revolutions.John Locke, born in 1632 in England, is often called the father of liberalism...", img: lockeImg, id: 15 },
  { name: "Montesquieu", years: "(1689–1755)", quote: "To become truly great, one has to stand with people, not above them.", bio: "In 18th-century France, Montesquieu studied governments like a scientist. Born in 1689, he warned of tyranny and praised the separation of powers—executive, legislative, judicial. His ideas became the blueprint for modern democracies, influencing constitutions across the world.In 18th-century France, Montesquieu studied governments like a scientist...", img: montesqueImg, id: 16 },
  { name: "Ramanuja", years: "(1017–1137)", quote: "Devotion is the path to liberation.", bio: "In 11th-century southern India, Ramanuja taught that devotion (bhakti) is the path to the divine. Born in 1017, he offered a warm alternative to cold logic—arguing that God is both personal and cosmic. His vision of “qualified non-dualism” shaped Hindu theology and spiritual practice for generations.In 11th-century southern India, Ramanuja taught that devotion (bhakti) is the path to the divine...", img: ramanujaImg, id: 17 },
  { name: "Adi Shankara", years: "(788–820)", quote: "Brahman is the only truth, the world is illusion.", bio: "Born around 788 AD in Kerala, India, Adi Shankara was a child prodigy turned wandering monk. He revitalized Hinduism by teaching Advaita Vedanta: everything is one, and that one is Brahman. The world is illusion, he said—liberation comes from seeing through it.Born around 788 AD in Kerala, India, Adi Shankara was a child prodigy...", img: sankaraImg, id: 18 },
  { name: "Arthur Schopenhauer", years: "(1788–1860)", quote: "Compassion is the basis of morality.", bio: "In 19th-century Germany, Schopenhauer looked at the world and saw suffering. Born in 1788, he believed human desire was endless and often painful. But his bleak outlook held a strange beauty—he saw compassion as our only salvation. His work later inspired psychologists and artists alike.In 19th-century Germany, Schopenhauer looked at the world and saw suffering...", img: schopenhauerImg, id: 19 },
  { name: "Baruch Spinoza", years: "(1632–1677)", quote: "The more you struggle to live, the less you live...", bio: "Spinoza, born in 1632 in Amsterdam, saw the divine not in temples but in nature itself. Expelled from his Jewish community for his radical views, he quietly wrote about a universe where God and Nature were one. For him, freedom came through understanding. He lived simply and thought deeply.Spinoza, born in 1632 in Amsterdam, saw the divine not in temples but in nature itself...", img: spinozaImg, id: 20 },
  { name: "Voltaire", years: "(1694–1778)", quote: "I disapprove of what you say...", bio: "Voltaire lit up Enlightenment France with his wit and fire. Born in 1694, he wrote plays, essays, and satire that mocked tyranny and championed reason. Jailed and exiled, he never stopped fighting for free speech and religious tolerance. His sharp pen reshaped the moral imagination of Europe.", img: voltaireImg, id: 21 },
  { name: "René Descartes", years: "(1596–1650)", quote: "I think, therefore I am.", bio: "In a cold room in 17th-century France, Descartes sat by a stove and questioned everything. Born in 1596, he sought certainty in a world of doubt. “I think, therefore I am,” he concluded—a foundation for modern philosophy. He was also a mathematician, linking geometry and algebra. Reason, for him, was the path to truth.In a cold room in 17th-century France, Descartes sat by a stove and questioned everything...", img: descartesImg, id: 22 },
  { name: "Jan Hus", years: "(1372–1415)", quote: "Seek the truth, listen to the truth...", bio: "Jan Hus, born around 1372 in Bohemia (now the Czech Republic), preached reform before Luther. He wanted a purer church, one grounded in scripture. His ideas threatened the church’s power, and he was burned at the stake in 1415. But his legacy lived on—he planted seeds of Protestantism long before it took root.Jan Hus, born around 1372 in Bohemia (now the Czech Republic)...", img: husImg, id: 23 },
  { name: "Alan Watts", years: "(1915–1973)", quote: "Trying to define yourself is like trying to bite your own teeth.", bio: "In the 20th century, Alan Watts bridged East and West. Born in 1915 in England, he moved to the U.S. and made Zen, Taoism, and Vedanta understandable to Western audiences. His talks flowed like rivers—playful, profound, poetic. He taught that you are not separate from the world—you are it.In the 20th century, Alan Watts bridged East and West...", img: wattsImg, id: 24 },
  { name: "Epicurus", years: "(341–270 BC)", quote: "Do not spoil what you have by desiring what you have not.", bio: "EEpicurus, born in 341 BC in Greece, believed happiness came from simple pleasures and peace of mind. He taught in a garden, welcoming everyone—even women and slaves. Contrary to modern misreadings, he didn’t promote indulgence but calm: enjoy life, avoid fear, and don’t worry about the gods.picurus, born in 341 BC in Greece, believed happiness came from simple pleasures...", img: epicurusImg, id: 25 },
  { name: "Pythagoras", years: "(c. 570–495 BC)", quote: "Do not say a little in many words but a great deal in a few.", bio: "Pythagoras, the math mystic, was born around 570 BC in Samos. He believed numbers were sacred and that harmony ruled the universe. He founded a secretive school where math, music, and morality blended. Most remember his triangle theorem, but he saw math as a path to the divine.", img: pythagorasImg, id: 26 },
  { name: "Karl Marx", years: "(1818–1883)", quote: "Philosophers have only interpreted the world...", bio: "In the smoky cities of 19th-century Europe, Karl Marx saw factory workers struggle and asked why. Born in 1818 in Germany, he challenged capitalism and wrote The Communist Manifesto with Engels. He believed that history moved through class struggles—and envisioned a society without exploitation.", img: marxImg, id: 28 },
  { name: "Laozi", years: "(6th century BC)", quote: "A journey of a thousand miles begins with a single step.", bio: "Legend says Laozi was born old and wise, sometime in the 6th century BC in China. He rode a water buffalo westward and wrote the Tao Te Ching before vanishing into the mountains. He taught that nature flows effortlessly, and so should we. Let go. Flow like water. That was his message.", img: laoziImg, id: 29 },
  { name: "Aldous Huxley", years: "(1894–1963)", quote: "Facts do not cease to exist because they are ignored.", bio: "Aldous Huxley, born in 1894 in England, peered into the future and didn't like what he saw. His novel Brave New World warned of comfort that numbs the soul. He explored science, mysticism, and psychedelics, seeking deeper truths about human potential and consciousness.", img: huxleyImg, id: 30 },
  { name: "Friedrich Nietzsche", years: "(1844–1900)", quote: "He who has a why to live can bear almost any how.", bio: "Nietzsche, born in 1844 in Germany, wrote like a poet and thought like a storm. He questioned morality, religion, and truth itself. “God is dead,” he declared—not in hatred, but to awaken people to build their own meaning. His ideas still echo, wild and brilliant, in the search for purpose.", img: nietzscheImg, id: 31 },
  { name: "Immanuel Kant", years: "(1724–1804)", quote: "Science is organized knowledge. Wisdom is organized life.", bio: "In quiet Königsberg (now Kaliningrad), Immanuel Kant lived a life of precision. Born in 1724, he rarely left his hometown but reshaped philosophy. He asked: What can we know? What should we do? What can we hope for? He believed morality came from duty, guided by reason.", img: kantImg, id: 32 },
  { name: "Friedrich Engels", years: "(1820–1895)", quote: "An ounce of action is worth a ton of theory.", bio: "Engels was Marx’s closest ally—born in 1820 in Germany, he saw the same injustice and wanted change. A writer, activist, and industrialist’s son, he used his wealth to support Marx. Together, they imagined a world free of class oppression. Engels gave socialism not only theory but heart and backing.", img: engelsImg, id: 34 },
  { name: "Thomas Aquinas", years: "(1225–1274)", quote: "To one who has faith, no explanation is necessary...", bio: "In 13th-century Italy, Thomas Aquinas tried to harmonize faith and reason. A Dominican friar born in 1225, he studied Aristotle and blended his logic with Christian theology. His Summa Theologica asked huge questions—What is God? What is good?—and answered them with calm clarity. He saw no contradiction between science and belief.", img: aquinasImg, id: 35 },
  { name: "Ashvaghosha", years: "(1st–2nd century AD)", quote: "Delusion creates the world. Enlightenment dissolves it.", bio: "Poet, philosopher, and playwright—Ashvaghosha lived in India around the 1st–2nd century AD. As a Buddhist thinker, he believed in the power of storytelling to awaken the spirit. His work Buddhacarita told the Buddha’s life story, emphasizing enlightenment as freedom from illusion.", img: ashvaghoshaImg, id: 36 },
  { name: "Niccolò Machiavelli", years: "(1469–1527)", quote: "It is better to be feared than loved, if you cannot be both.", bio: "Born in 1469 in Florence, Machiavelli knew power up close. A diplomat and realist, he wrote The Prince as a brutally honest guide to politics. Better to be feared than loved, he said, if you must choose. To him, politics was about outcomes, not ideals—a perspective still debated today.", img: machiavelliImg, id: 37 },
  { name: "John Calvin", years: "(1509–1564)", quote: "There is no knowing that does not begin with knowing God.", bio: "Calvin, born in 1509 in France, was a sharp legal mind turned theologian. He led the Protestant Reformation with an emphasis on God’s absolute sovereignty. In Geneva, he shaped a city into a spiritual republic. His ideas—like predestination—were strict, but they gave many people structure and purpose in a chaotic age.", img: calvinImg, id: 38 },
  { name: "Erasmus of Rotterdam", years: "(1466–1536)", quote: "The main hope of a nation lies in the proper education of its youth.", bio: "Erasmus, born in 1466 in the Netherlands, was a priest with a humanist heart. He believed the Church needed reform—but not revolt. Through satire and scholarship, he called for education, tolerance, and inner piety. His book In Praise of Folly poked fun at corruption, hoping to awaken change from within.", img: erasmusImg, id: 39 },
  { name: "Marcus Aurelius", years: "(121–180 AD)", quote: "You have power over your mind – not outside events...", bio: "Marcus Aurelius, a Roman emperor born in 121 AD, ruled with wisdom during war and plague. At night, he wrote to himself—not as a ruler, but as a Stoic. His Meditations are a manual for inner strength: control your mind, accept what you can't change, and do your duty with grace.Marcus Aurelius, a Roman emperor born in 121 AD, ruled with wisdom during war and plague. At night, he wrote to himself—not as a ruler, but as a Stoic. His Meditations are a manual for inner strength: control your mind, accept what you can't change, and do your duty with grace.Marcus Aurelius, a Roman emperor born in 121 AD, ruled with wisdom during war and plague. At night, he wrote to himself—not as a ruler, but as a Stoic. His Meditations are a manual for inner strength: control your mind, accept what you can't change, and do your duty with grace.", img: aureliusImg, id: 40 },
  { name: "Cicero", years: "(106–43 BC)", quote: "The welfare of the people is the highest law.",bio: "In the final days of the Roman Republic, Cicero stood as its conscience—an orator, lawyer, and philosopher who believed that words could guide empires. Born in 106 BC, he rose from humble beginnings to become Rome’s greatest speaker, wielding his pen and voice to defend liberty, reason, and the rule of law. Through turbulent politics, he upheld the ideals of justice and civic duty. He believed that a republic must be rooted in virtue, not ambition. Even as chaos closed in and tyranny silenced dissent, Cicero chose principle over safety. His writings on ethics, law, and the soul would echo through centuries, shaping the minds of thinkers from Augustine to Jefferson.",img: ciceroIMG, id: 41 },
];
